# This is a sample workflow to help test contributions
# Change the branch name, url and token to fit with your own environment

# To run this locally with act use:
#     act workflow_dispatch -j local-test
#
# If you have permissions, you can run this workflow via the GitHub UI.
# Otherwise, use 'on: push' instead of 'on: workflow_dispatch'.

# Don't forget to revert the file changes and invalidate any tokens that were
# committed before opening a pull request.
on: workflow_dispatch

name: local-test

jobs:
  local-test:
    name: local-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

    - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: '20.9.0'

    - name: NPM Install
      run: npm ci

    - name: NPM Build
      run: npm run build

    - name: Setup Vault
      run: node ./integrationTests/e2e/setup.js
      env:
        VAULT_HOST: localhost
        VAULT_PORT: 8200

    - name: Import Secrets
      id: import-secrets
      # use the local changes
      uses: ./
      # run against a specific version of vault-action
      # uses: hashicorp/vault-action@v2.1.2
      with:
        url: http://localhost:8200
        method: token
        token: testtoken
        secrets: |
          secret/data/test-json-string jsonString;

    - name: Check Secrets
      run: |
        touch secrets.json
        echo "${{ steps.import-secrets.outputs.jsonString }}" >> secrets.json

    - name: Check json file format
      run: |
        echo
        cat secrets.json
        jq -c . < secrets.json

  revoke-token:
    name: revoke-token
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

    - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: '16.14.0'

    - name: NPM Install
      run: npm ci

    - name: NPM Build
      run: npm run build

    - name: Setup Vault
      run: node ./integrationTests/e2e/setup.js
      env:
        VAULT_HOST: localhost
        VAULT_PORT: 8200

    - name: Import Secrets
      id: import-secrets
      # use the local changes
      uses: ./
      # run against a specific version of vault-action
      # uses: hashicorp/vault-action@v2.1.2
      with:
        url: http://localhost:8200
        method: token
        token: testtoken
        revokeToken: true
